---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "12:25"
  - package-ecosystem: npm
    directory: "/javascript"
    schedule:
      interval: "daily"
      time: "12:25"
  - package-ecosystem: bundler
    directory: "/ruby"
    schedule:
      interval: "daily"
      time: "12:25"
